// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationEntrenadorPokemon;

#nullable disable

namespace WebApplicationEntrenadorPokemon.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240731223100_EntidadEntrenadoryPokemonRelaciones")]
    partial class EntidadEntrenadoryPokemonRelaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplicationEntrenadorPokemon.Entidades.Entrenador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EntrenadorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId")
                        .IsUnique();

                    b.ToTable("Entrenador");
                });

            modelBuilder.Entity("WebApplicationEntrenadorPokemon.Entidades.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("WebApplicationEntrenadorPokemon.Entidades.Pokemon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("EntrenadorId")
                        .HasColumnType("int");

                    b.Property<int>("altura")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("officialArtwork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("peso")
                        .HasColumnType("int");

                    b.Property<string>("tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("EntrenadorId");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("WebApplicationEntrenadorPokemon.Entidades.TipoPokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("tipoPokemon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposPokemon");
                });

            modelBuilder.Entity("WebApplicationEntrenadorPokemon.Entidades.Entrenador", b =>
                {
                    b.HasOne("WebApplicationEntrenadorPokemon.Entidades.Genero", "Genero")
                        .WithOne("Entrenador")
                        .HasForeignKey("WebApplicationEntrenadorPokemon.Entidades.Entrenador", "GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("WebApplicationEntrenadorPokemon.Entidades.Pokemon", b =>
                {
                    b.HasOne("WebApplicationEntrenadorPokemon.Entidades.Entrenador", "Entrenador")
                        .WithMany("Pokemon")
                        .HasForeignKey("EntrenadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("WebApplicationEntrenadorPokemon.Entidades.Entrenador", b =>
                {
                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("WebApplicationEntrenadorPokemon.Entidades.Genero", b =>
                {
                    b.Navigation("Entrenador");
                });
#pragma warning restore 612, 618
        }
    }
}
